# Generated by Django 5.2.3 on 2025-06-22 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_amount_alter_payment_course_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="methods",
            new_name="method",
        ),
    ]
