# Generated by Django 5.2.3 on 2025-06-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_lesson_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
